version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: ./scripts/before_install.sh
      timeout: 900
  AfterInstall:
    - location: ./scripts/after_install.sh  
      timeout: 900
  ValidateService:
    - location: ./scripts/validate_install.sh    
      timeout: 900 